### PR TITLE
busta

### PR DESCRIPTION
**Pull request by Big-Clutch**

### CODE REVIEW

**Review by TheLastLoad — CHANGES_REQUESTED** [review]
leave only hello world

**Comment by Big-Clutch** [comment]
ok

**Review by TheLastLoad — APPROVED** [review]
AMAZING

**Comment by Big-Clutch** [comment]
I want a raise

**Review by TheLastLoad — APPROVED** [review]

**Review by TheLastLoad — APPROVED** [review]

**Pull request merged**
